name: Build Release 
on:
  push:
    branches: 
    - master
    tags:
    - 'v*'
  pull_request:
    branches:
    - master
    tags:
    - 'v*'

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Checkout code
      uses: actions/checkout@v6.0.1

    - name: Set up JDK 17
      uses: actions/setup-java@v5.1.0
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Create secrets.properties file
      run: |
        echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" > secrets.properties

    - name: Change permission of gradlew script
      run: chmod +x gradlew

    - name: Build release APK
      run: ./gradlew assembleRelease

    - name: Find the APK file path
      id: find_apk
      run: |
        APK_PATH=$(find app/build/outputs/apk/release/ -name "*.apk" | head -n 1)
        echo "Found APK at: $APK_PATH"
        echo "apk_path=$APK_PATH" >> $GITHUB_OUTPUT

    - name: Upload Artifact
      uses:  actions/upload-artifact@v5.0.0
      with:
        name: app-release
        path: ${{ steps.find_apk.outputs.apk_path }}

    - name: Create GitHub Release and Upload APK 
      run: |
        APK_PATH=${{ steps.find_apk.outputs.apk_path }}
        TAG_NAME=${{ github.ref_name }}

        gh release create $TAG_NAME "$APK_PATH#app-release.apk" \
          --title "Release $TAG_NAME" \
          --notes "Automated build of version $TAG_NAME."
    
